# Generated by Django 3.2 on 2022-04-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_monthly_expanses_data_monthly_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='attachment',
            field=models.FileField(default=True, upload_to=''),
        ),
    ]
