# Generated by Django 3.2.5 on 2022-04-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_data_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='attachment',
        ),
    ]
